# Generated by Django 4.2.7 on 2023-12-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='sub_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subproject'),
        ),
    ]
