# Generated by Django 4.2.8 on 2023-12-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='tag',
            field=models.ManyToManyField(to='core.tag'),
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(to='core.tag'),
        ),
    ]
