# Generated by Django 4.2.13 on 2024-12-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_task_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-position']},
        ),
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.BigIntegerField(),
        ),
    ]
