# Generated by Django 4.2.13 on 2024-12-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_task_options_alter_task_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
